version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: "${USER_NAME}"
        USER_ID: "${HOST_UID}"
        GROUP_ID: "${HOST_GID}"
        BASE_IMAGE: "ubuntu:22.04"
    container_name: vamr_project_container
    volumes:
      - ..:/home/dev/
    working_dir: /home/dev/
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
